server:
  port: 8081
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    compatibility-verifier:
      enabled:  false
  application:
    name: eureka-order